name: "database"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

env:
  CURRENT_SEMESTER: 20262

jobs:
  update-db:
    name: Update database
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate
        run: |
          docker run --rm -v "${PWD}:/work" -w /work/db/src \
            -e CURRENT_SEMESTER="${CURRENT_SEMESTER}" \
            caravelahc/matrufsc:latest bash -c '
              set -e
              virtualenv --python=/usr/bin/python2 /tmp/venv
              source /tmp/venv/bin/activate
              pip install bs4
              ./get_turmas.py ${CURRENT_SEMESTER}
              ./parse_turmas.py ${CURRENT_SEMESTER}_*.xml /work/${CURRENT_SEMESTER}.json
              chmod -R a+rw /work/${CURRENT_SEMESTER}.json /work/db/src
            '
          wc -c ${CURRENT_SEMESTER}.json
      - name: Publish
        run: |
          git config user.email 53460931+caravelabot@users.noreply.github.com
          git config user.name caravelabot
          rm -f db/src/*.xml
          git checkout gh-pages
          mv ${CURRENT_SEMESTER}.json data/${CURRENT_SEMESTER}.json
          git add -f data/${CURRENT_SEMESTER}.json
          git commit -m "Update ${CURRENT_SEMESTER}.json" || true
          git push origin gh-pages
