name: "deploy"
on:
  push:
    branches: [master]

jobs:
  deploy-gh-pages:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Compile
        run: |
          ./configure --base-path=bin
          SITE_PATH=bin make
      - name: Deploy
        run: |
          git config user.email 53460931+caravelabot@users.noreply.github.com
          git config user.name caravelabot
          REV=$(git log -n1 --format=format:'%h' HEAD)
          git checkout -f gh-pages
          cp bin/* .
          git add -u
          git commit -m "Deploy ${REV}" || true
          git push origin gh-pages
